name: Final Push
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Files
        run: |
          mkdir -p suitcase
          pip download stable-audio-tools --platform win_amd64 --python-version 310 --only-binary=:all: --dest ./suitcase
          zip -r everything.zip suitcase/
          split -b 40M everything.zip "part_"
          mkdir -p final_zip_parts
          mv part_* final_zip_parts/
      - name: Commit
        run: |
          git config --global user.name "robot"
          git config --global user.email "robot@github.com"
          git add final_zip_parts/*
          git commit -m "done"
          git push
